# Generated by Django 4.2.27 on 2026-01-31 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="📦", max_length=50)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("is_income", models.BooleanField(default=False)),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords that help AI categorize transactions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(max_length=500)),
                ("merchant", models.CharField(blank=True, max_length=255)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("expense", "Expense"), ("income", "Income")],
                        default="expense",
                        max_length=10,
                    ),
                ),
                ("ai_categorized", models.BooleanField(default=False)),
                (
                    "ai_confidence",
                    models.FloatField(default=0.0, help_text="AI confidence score 0-1"),
                ),
                ("ai_suggested_category", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("plaid", "Bank Sync (Plaid)"),
                            ("receipt", "Receipt Scan"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "plaid_transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.category",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="receipts.receipt",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["date"], name="transaction_date_7edf95_idx"),
                    models.Index(
                        fields=["category"], name="transaction_categor_bf503b_idx"
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="transaction_transac_ddda52_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("alert_at_percentage", models.IntegerField(default=80)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="transactions.category",
                    ),
                ),
            ],
            options={
                "db_table": "budgets",
                "unique_together": {("category", "period")},
            },
        ),
    ]
