# Generated by Django 4.2.27 on 2026-01-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="ai_categorized",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="ai_confidence",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="ai_suggested_category",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="plaid_transaction_id",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual Entry"), ("receipt", "Receipt Scan")],
                default="manual",
                max_length=20,
            ),
        ),
    ]
